version: '3'


services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile.heroku
    env_file:
      - ./.envs/.heroku/.django
      - ./.envs/.heroku/.postgres
